.TH RUFUX 1 "September 2026" "Rufux 1.0.0" "User Commands"
.SH NAME
rufux \- bootable USB creator for Linux (Rufus port)
.SH SYNOPSIS
.B rufux
\fIlist\fR [\-\-json] [\-\-allow\-fixed]
.br
.B rufux
\fIprobe\fR \fIFILE\fR [\-\-detail]
.br
.B rufux
\fIchecksum\fR \fIFILE\fR
.br
.B rufux
\fIwrite\fR \fISRC DST\fR [\-\-dry\-run|\-\-real] [\-\-verify] [\-\-allow\-fixed] [\-\-allow\-file] [\-\-yes]
.br
.B rufux
\fIpartition\fR \fIDST\fR \-\-scheme gpt|dos \-\-layout single|esp+main [\-\-real] [\-\-yes] ...
.br
.B rufux
\fIformat\fR \fIDST\fR \-\-fs vfat|ntfs|exfat|ext4|udf [\-\-label \fIL\fR] [\-\-real] [\-\-yes] ...
.br
.B rufux
\fIextract\fR \fISRC\fR \fIDEST_DIR\fR [\-\-dry\-run]
.br
.B rufux
\fIinstall\-boot\fR \fIDST\fR \-\-mbr bios|gpt [\-\-real] [\-\-yes] ...
.br
.B rufux
\fIpersist\fR \fIDIR\fR \-\-size \fIMB\fR [\-\-label \fIL\fR] [\-\-dry\-run]
.br
.B rufux
\fIbadblocks\fR \fIDST\fR [\-\-allow\-file]
.br
.B rufux
\fImount\fR|\fIumount\fR \fIDEV\fR [\-\-dry\-run]
.br
.B rufux
\fIsecureboot\-status\fR
.br
.B rufux
\fIvalidate\-efi\fR \fIFILE\fR
.br
.B rufux
\fIupdate\-check\fR
.br
.B rufux
\fIcreate\fR \fISRC DST\fR \-\-mode dd|extract [\-\-scheme \fIS\fR] [\-\-fs \fIF\fR] [\-\-persist\-mb \fIN\fR] ...
.br
.B rufux
\fI\-\-gui\fR [\-\-theme system|dark|light]
.SH DESCRIPTION
Rufux creates bootable USB drives on Linux. Destructive commands default to
\fB\-\-dry\-run\fR planning; real block-device writes need \fB\-\-real \-\-yes\fR
and root (sudo/pkexec). The GUI re-launches itself as root via pkexec
when started unprivileged, so all operations work out of the box.
.SH EXAMPLES
List removable drives:
.PP
.RS
rufux list
.RE
.PP
Write an image (dry\-run first, then real with verify):
.PP
.RS
rufux write linux.iso /dev/sdb --dry\-run
.br
sudo rufux write linux.iso /dev/sdb --real --verify --yes
.RE
.PP
UEFI file flow with auto-mount (Phase 3):
.PP
.RS
sudo rufux create linux.iso /dev/sdb --mode extract --scheme gpt --fs vfat --yes
.RE
.SH "SEE ALSO"
.BR udisksctl (1),
.BR sfdisk (8),
.BR mkfs.vfat (8)
.SH AUTHOR
Rufux contributors; upstream Rufus by Pete Batard. GPLv3.
